name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive  # Fetch Hugo themes (true OR recursive)

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.79.1'
          extended: true

      - name: Build
        run: hugo --minify --cleanDestinationDir

      - name: Setup Rclone
        run: |
          sudo apt-get install -y -qq rclone
          mkdir /home/runner/.config/rclone
          echo "${{ secrets.RCLONE_CONF }}" > ~/.config/rclone/rclone.conf
          
      - name: Deploy to Prod (if on main)
        if: github.ref == 'refs/heads/main'
        run: rclone sync ./public aldeploy:www
